-- Tabela APP_USER
CREATE TABLE APP_USER (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

-- Tabela CATEGORY
CREATE TABLE CATEGORY (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

-- Tabela NEWS
CREATE TABLE NEWS (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    SUMMARY TEXT,
    AUTHOR VARCHAR(255),
    DATE DATE NOT NULL,
    TIME TIME NOT NULL,
    IMAGE BYTEA,
    IMAGE_DESC TEXT,
    CONTENT TEXT NOT NULL
);

-- Tabela CATEGORY_NEWS
CREATE TABLE CATEGORY_NEWS (
    ID SERIAL PRIMARY KEY,
    CATEGORY_ID INT NOT NULL,
    NEWS_ID INT NOT NULL,
    CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
    CONSTRAINT FK_NEWS FOREIGN KEY (NEWS_ID) REFERENCES NEWS (ID)
);

-- Tabela USER_NOTIFICATION
CREATE TABLE USER_NOTIFICATION (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    NOTIFICATION TEXT NOT NULL,
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID)
);

-- Tabela MARKED_NEWS
CREATE TABLE MARKED_NEWS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    NEWS_ID INT NOT NULL,
    CONSTRAINT FK_USER_MARKED FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID),
    CONSTRAINT FK_NEWS_MARKED FOREIGN KEY (NEWS_ID) REFERENCES NEWS (ID)
);

-- Tabela CATEGORY_OF_INTEREST
CREATE TABLE CATEGORY_OF_INTEREST (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    CONSTRAINT FK_USER_INTEREST FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID),
    CONSTRAINT FK_CATEGORY_INTEREST FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
);